from tkinter import *

root = Tk()
menu = Menu(root)

root.config(menu=menu)
filemenu = Menu(menu)

menu.add_cascade(label='File', menu=filemenu)
filemenu.add_command(label='New')
filemenu.add_command(label='open...')
filemenu.add_separator()
filemenu.add_command(label='Exit', command=root.quit)

helpmenu = Menu(menu)
menu.add_cascade(label='Help', menu=helpmenu)
helpmenu.add_command(label='About')

viewmenu = Menu(menu)
toolmenu = Menu(menu)
appearancemenu = Menu(menu)
statusbarmenu =Menu(menu)
activeeditormenu = Menu(menu)
bidimenu = Menu(menu)
menu.add_cascade(label='View', menu=viewmenu)
viewmenu.add_cascade(label='Tool Windows', menu=toolmenu)
toolmenu.add_command(label='Project')
toolmenu.add_command(label='Bookmarks')
toolmenu.add_command(label='Find')
toolmenu.add_command(label='Run')
toolmenu.add_command(label='Debug')
toolmenu.add_command(label='Problems')
toolmenu.add_command(label='Structure')
toolmenu.add_command(label='Services')
toolmenu.add_command(label='Version Control')
toolmenu.add_command(label='Hierachy')
toolmenu.add_command(label='Learn')
toolmenu.add_command(label='Notifications')
toolmenu.add_command(label='Python Console')
toolmenu.add_command(label='Python Package')
toolmenu.add_command(label='Terminal')
toolmenu.add_command(label='TODO')
viewmenu.add_cascade(label='Appearance', menu=appearancemenu)
appearancemenu.add_command(label='Enter Presentation Mode')
appearancemenu.add_command(label='Enter Distraction Free Mode')
appearancemenu.add_command(label='Enter Full Screen')
appearancemenu.add_command(label='Enter Zen Mode')
appearancemenu.add_command(label='Main menu')
appearancemenu.add_command(label='Toolbar')
appearancemenu.add_command(label='Navigation Bar')
appearancemenu.add_command(label='Tool Window Bars')
appearancemenu.add_command(label='Status Bar')
appearancemenu.add_cascade(label='Status Bar Widgets', menu=statusbarmenu)
statusbarmenu.add_command(label='Code With Me Wire Stats')
statusbarmenu.add_command(label='Line:Column Number')
statusbarmenu.add_command(label='Line Separator')
statusbarmenu.add_command(label='File Encoding')
statusbarmenu.add_command(label='Power Save Mode')
statusbarmenu.add_command(label='Editor Selection Mode')
statusbarmenu.add_command(label='Indentation')
statusbarmenu.add_command(label='JSON Schema')
statusbarmenu.add_command(label='Python Interpreter')
statusbarmenu.add_command(label='Read-Only Attribute')
statusbarmenu.add_command(label='Memory Indicator')
appearancemenu.add_command(label='Details In Tree View')
appearancemenu.add_command(label='Members In Navigation Bar')
viewmenu.add_separator()
viewmenu.add_command(label='Quick Definition')
viewmenu.add_command(label='Quick Type Definition')
viewmenu.add_command(label='Parameter Info')
viewmenu.add_command(label='Type Info')
viewmenu.add_command(label='Context Info')
viewmenu.add_command(label='Recent Files')
viewmenu.add_command(label='Recently Changed Files')
viewmenu.add_command(label='Receent Locations')
viewmenu.add_command(label='Recent Changes')
viewmenu.add_separator()
viewmenu.add_command(label='Compare With')
viewmenu.add_command(label='Compare With Clipboard')
viewmenu.add_separator()
viewmenu.add_command(label='Quick Switch Scheme')
viewmenu.add_cascade(label='Active Editor', menu=activeeditormenu)
activeeditormenu.add_command(label='Soft-Wrap')
activeeditormenu.add_command(label='Show Whitespace')
activeeditormenu.add_command(label='Show Line Numbers')
activeeditormenu.add_command(label='Show Gutter Icons')
activeeditormenu.add_command(label='Show Indent Guide')
activeeditormenu.add_command(label='Show Import Popups')
activeeditormenu.add_command(label='Show BreadCrumbs')
activeeditormenu.add_separator()
activeeditormenu.add_command(label='Increase Font Size')
activeeditormenu.add_command(label='Decrease Font Size')
viewmenu.add_separator()
viewmenu.add_command(label='Increase Font Size In All Editors')
viewmenu.add_command(label='Decrease Font Size In All Editors')
viewmenu.add_command(label='Reset Font Size')
viewmenu.add_separator()
viewmenu.add_cascade(label='Bidi Text Base Direction', menu=bidimenu)
bidimenu.add_command(label='Content-Based')
bidimenu.add_command(label='Left-To-Right')
bidimenu.add_command(label='Right-To-Left')
mainloop()